#!/usr/bin/env bash
# ESMFold environment setup on the cluster -- installs into the SAME
# active env `source cluster/env_activate.sh` gives you (so no second
# activation step in the normal workflow), but physically places every
# installed file on scratch via `pip install --target=`, not in that
# env's own site-packages under $HOME. Confirmed live this matters: a
# plain `pip install torch` into the existing env (faire-agent, under
# /home/hmp278/miniforge3/envs/faire-agent) hit "OSError: [Errno 122]
# Disk quota exceeded" partway through (torch + its deps are several GB).
# --target sidesteps that entirely -- the files never touch $HOME, only
# PYTHONPATH points the existing interpreter at them.
#
# Uses HuggingFace transformers' EsmForProteinFolding rather than Meta's
# original fair-esm[esmfold] package deliberately: the original needs
# openfold's custom CUDA attention kernels compiled against the exact
# local CUDA/PyTorch version, a common source of cluster-install
# failures; the transformers port reimplements the same model in plain
# PyTorch with no custom kernel compilation step. See
# structure_prediction/run_esmfold.py's own docstring for the same note.
#
# Usage:
#   source cluster/env_activate.sh
#   ./cluster/install_esmfold.sh
#
# Every later interactive use of these packages (not just this install
# script) needs the same PYTHONPATH set -- cluster/run_esmfold.sbatch
# already does this itself, but if you import torch/transformers by hand
# in a login-node shell, `source cluster/esmfold_pythonpath.sh` first
# (written by this script, see the bottom).
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root (PHA_Ocean_Atlas/)

SCRATCH_BASE="${SCRATCH_BASE:-/scratch/morrill/users/hmp278}"
PKG_DIR="${PKG_DIR:-${SCRATCH_BASE}/esmfold_packages}"
export HF_HOME="${HF_HOME:-${SCRATCH_BASE}/hf_cache}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-${SCRATCH_BASE}/pip_cache}"
mkdir -p "${PKG_DIR}" "${HF_HOME}" "${PIP_CACHE_DIR}"

if [ -z "${VIRTUAL_ENV:-}" ] && [ -z "${CONDA_DEFAULT_ENV:-}" ]; then
  echo "No active env detected -- run 'source cluster/env_activate.sh' first" >&2
  echo "(from cluster/setup_env.sh's pha-reference env), then re-run this script." >&2
  exit 2
fi
echo "Active env: ${CONDA_DEFAULT_ENV:-${VIRTUAL_ENV}}"
echo "Package install target (on scratch, NOT the env's own site-packages): ${PKG_DIR}"
echo "Pip download/build cache (on scratch): ${PIP_CACHE_DIR}"

# CUDA 12.1 build -- matches what's been used elsewhere on this project's
# gpu-a100 partition (see cluster/install_mmseqs2.sh's GPU-variant notes);
# adjust the index-url below if the cluster's actual CUDA toolkit differs.
echo "Installing PyTorch (CUDA 12.1 build) to ${PKG_DIR} ..."
pip install --target="${PKG_DIR}" --index-url https://download.pytorch.org/whl/cu121 torch

echo "Installing transformers + supporting packages to ${PKG_DIR} ..."
pip install --target="${PKG_DIR}" "transformers>=4.35" accelerate einops

# Persist PYTHONPATH (and the two cache dirs) so every later shell/sbatch
# job can just `source cluster/esmfold_pythonpath.sh` instead of
# re-deriving these paths -- run_esmfold.sbatch sources this itself.
cat > cluster/esmfold_pythonpath.sh <<EOF
# Generated by install_esmfold.sh -- source this (after cluster/env_activate.sh)
# before importing torch/transformers from the esmfold scratch install.
export PYTHONPATH="${PKG_DIR}\${PYTHONPATH:+:\${PYTHONPATH}}"
export HF_HOME="${HF_HOME}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR}"
EOF
echo "wrote cluster/esmfold_pythonpath.sh"

# shellcheck source=/dev/null
source cluster/esmfold_pythonpath.sh

echo
echo "Verifying import + CUDA visibility (no model download yet) ..."
python - <<'PYEOF'
import torch
print("torch:", torch.__version__, "CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("device:", torch.cuda.get_device_name(0))
import transformers
print("transformers:", transformers.__version__)
from transformers import EsmForProteinFolding  # import-only check, no download
print("EsmForProteinFolding import OK")
PYEOF

echo
echo "Environment ready -- packages live on scratch (${PKG_DIR}), imported into the"
echo "existing ${CONDA_DEFAULT_ENV:-${VIRTUAL_ENV}} env via PYTHONPATH. Nothing written to \$HOME."
echo
echo "Consider pre-warming the model-weight cache once interactively before the first real"
echo "sbatch array job, so 20+ concurrent array tasks don't all try to download the same"
echo "~2.7GB of weights at once:"
echo "  python -c \"from transformers import EsmForProteinFolding; EsmForProteinFolding.from_pretrained('facebook/esmfold_v1')\""
