#!/usr/bin/env bash
# Installs a static MMseqs2 binary into cluster/bin/ (no conda/bioconda
# channel, no compiler needed -- just a prebuilt release tarball from
# https://github.com/soedinglab/MMseqs2/releases). Needed by `pha-reference
# cluster95` (phaatlas/pipeline/cluster95.py). Run once, from a node with
# internet access (a login node, same as setup_env.sh itself).
#
# Usage:
#   ./cluster/install_mmseqs2.sh
#   MMSEQS_VARIANT=sse41 ./cluster/install_mmseqs2.sh   # older CPUs without AVX2
#   MMSEQS_VERSION=17-... ./cluster/install_mmseqs2.sh  # pin a specific release
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root (PHA_Ocean_Atlas/)

MMSEQS_VERSION="${MMSEQS_VERSION:-latest}"
# avx2 is the right default for virtually any x86_64 HPC node built since
# ~2013; override to sse41/sse2 only if `mmseqs` itself later crashes with
# an illegal-instruction error (the telltale sign the node's CPU predates
# the variant you installed), or to linux-arm64 on an ARM partition.
MMSEQS_VARIANT="${MMSEQS_VARIANT:-linux-avx2}"

mkdir -p cluster/bin
TMP_TAR="$(mktemp)"
trap 'rm -f "${TMP_TAR}"' EXIT

if [ "${MMSEQS_VERSION}" = "latest" ]; then
  URL="https://github.com/soedinglab/MMseqs2/releases/latest/download/mmseqs-${MMSEQS_VARIANT}.tar.gz"
else
  URL="https://github.com/soedinglab/MMseqs2/releases/download/${MMSEQS_VERSION}/mmseqs-${MMSEQS_VARIANT}.tar.gz"
fi

echo "Downloading ${URL} ..."
curl -fL -o "${TMP_TAR}" "${URL}"
tar xzf "${TMP_TAR}" -C cluster/bin --strip-components=2 mmseqs/bin/mmseqs

chmod +x cluster/bin/mmseqs
cluster/bin/mmseqs version

echo
echo "Installed: cluster/bin/mmseqs"
echo "cluster/env_activate.sh (generated by setup_env.sh) already puts cluster/bin on PATH --"
echo "re-run ./cluster/setup_env.sh if you installed this AFTER setup_env.sh, so it picks that up."
