#!/usr/bin/env bash
# Installs a static Foldseek binary -- same distribution model as
# cluster/install_mmseqs2.sh (same lab, Steinegger/Söding groups, same
# prebuilt-tarball-from-GitHub-releases approach): no conda/bioconda
# channel, no compiler, no Python env at all. Needed for the structure
# comparison step in figures/PHA_CLEAN_RESULTS.md section 6.3 (comparing
# ESMFold/ColabFold structures against the folded reference set).
#
# Usage:
#   ./cluster/install_foldseek.sh                              # AVX2 build -> cluster/bin/foldseek
#   FOLDSEEK_VARIANT=sse2 ./cluster/install_foldseek.sh         # older CPUs without AVX2
#   FOLDSEEK_VERSION=9-... ./cluster/install_foldseek.sh        # pin a specific release
#
# GPU build (Foldseek has an experimental GPU-accelerated search, separate
# from the CPU build the same way mmseqs2's GPU/CPU builds are separate --
# see install_mmseqs2.sh's own note on why those install to different
# directories rather than overwriting each other):
#   FOLDSEEK_VARIANT=linux-gpu FOLDSEEK_OUTPUT_DIR=cluster/bin-gpu ./cluster/install_foldseek.sh
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root (PHA_Ocean_Atlas/)

FOLDSEEK_VERSION="${FOLDSEEK_VERSION:-latest}"
FOLDSEEK_VARIANT="${FOLDSEEK_VARIANT:-linux-avx2}"
FOLDSEEK_OUTPUT_DIR="${FOLDSEEK_OUTPUT_DIR:-cluster/bin}"

mkdir -p "${FOLDSEEK_OUTPUT_DIR}"
TMP_TAR="$(mktemp)"
trap 'rm -f "${TMP_TAR}"' EXIT

if [ "${FOLDSEEK_VERSION}" = "latest" ]; then
  URL="https://github.com/steineggerlab/foldseek/releases/latest/download/foldseek-${FOLDSEEK_VARIANT}.tar.gz"
else
  URL="https://github.com/steineggerlab/foldseek/releases/download/${FOLDSEEK_VERSION}/foldseek-${FOLDSEEK_VARIANT}.tar.gz"
fi

echo "Downloading ${URL} ..."
curl -fL -o "${TMP_TAR}" "${URL}"
tar xzf "${TMP_TAR}" -C "${FOLDSEEK_OUTPUT_DIR}" --strip-components=2 foldseek/bin/foldseek

chmod +x "${FOLDSEEK_OUTPUT_DIR}/foldseek"
"${FOLDSEEK_OUTPUT_DIR}/foldseek" version

echo
echo "Installed: ${FOLDSEEK_OUTPUT_DIR}/foldseek"
if [ "${FOLDSEEK_OUTPUT_DIR}" = "cluster/bin" ]; then
  echo "cluster/env_activate.sh (generated by setup_env.sh) already puts cluster/bin on PATH --"
  echo "re-run ./cluster/setup_env.sh if you installed this AFTER setup_env.sh, so it picks that up."
else
  echo "Not on PATH automatically (only cluster/bin/ is) -- pass its full path explicitly."
fi
