#!/usr/bin/env bash
# Installs a static MMseqs2 binary (no conda/bioconda channel, no compiler
# needed -- just a prebuilt release tarball from
# https://github.com/soedinglab/MMseqs2/releases). Needed by `pha-reference
# cluster95` and `pha-reference gopc-build-db`/`gopc-search`. Run once per
# variant, from a node with internet access (a login node, same as
# setup_env.sh itself).
#
# Usage:
#   ./cluster/install_mmseqs2.sh                            # CPU build -> cluster/bin/mmseqs
#   MMSEQS_VARIANT=sse41 ./cluster/install_mmseqs2.sh        # older CPUs without AVX2
#   MMSEQS_VERSION=17-... ./cluster/install_mmseqs2.sh       # pin a specific release
#
# GPU build (needed for `gopc-search --gpu`, see cluster/run_gopc_search.sbatch)
# -- installs to a SEPARATE location (cluster/bin-gpu/) since it's a
# different binary than the CPU one, and both are needed: the CPU one for
# gopc-build-db (createdb doesn't need CUDA even for --createdb-mode 2 --
# GPU-compatible is a storage format choice, not a runtime requirement to
# WRITE), the GPU one for the actual search step:
#   MMSEQS_VARIANT=linux-gpu MMSEQS_OUTPUT_DIR=cluster/bin-gpu ./cluster/install_mmseqs2.sh
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root (PHA_Ocean_Atlas/)

MMSEQS_VERSION="${MMSEQS_VERSION:-latest}"
# avx2 is the right default for virtually any x86_64 HPC node built since
# ~2013; override to sse41/sse2 only if `mmseqs` itself later crashes with
# an illegal-instruction error (the telltale sign the node's CPU predates
# the variant you installed), or to linux-arm64 on an ARM partition, or to
# linux-gpu for CUDA-accelerated search (see above -- install that to a
# separate MMSEQS_OUTPUT_DIR, don't let it overwrite the CPU build).
MMSEQS_VARIANT="${MMSEQS_VARIANT:-linux-avx2}"
MMSEQS_OUTPUT_DIR="${MMSEQS_OUTPUT_DIR:-cluster/bin}"

mkdir -p "${MMSEQS_OUTPUT_DIR}"
TMP_TAR="$(mktemp)"
trap 'rm -f "${TMP_TAR}"' EXIT

if [ "${MMSEQS_VERSION}" = "latest" ]; then
  URL="https://github.com/soedinglab/MMseqs2/releases/latest/download/mmseqs-${MMSEQS_VARIANT}.tar.gz"
else
  URL="https://github.com/soedinglab/MMseqs2/releases/download/${MMSEQS_VERSION}/mmseqs-${MMSEQS_VARIANT}.tar.gz"
fi

echo "Downloading ${URL} ..."
curl -fL -o "${TMP_TAR}" "${URL}"
tar xzf "${TMP_TAR}" -C "${MMSEQS_OUTPUT_DIR}" --strip-components=2 mmseqs/bin/mmseqs

chmod +x "${MMSEQS_OUTPUT_DIR}/mmseqs"
"${MMSEQS_OUTPUT_DIR}/mmseqs" version

echo
echo "Installed: ${MMSEQS_OUTPUT_DIR}/mmseqs"
if [ "${MMSEQS_OUTPUT_DIR}" = "cluster/bin" ]; then
  echo "cluster/env_activate.sh (generated by setup_env.sh) already puts cluster/bin on PATH --"
  echo "re-run ./cluster/setup_env.sh if you installed this AFTER setup_env.sh, so it picks that up."
else
  echo "Not on PATH automatically (only cluster/bin/ is) -- pass its full path via --mmseqs-bin"
  echo "(cluster/run_gopc_search.sbatch does this for you when run on the gpu-a100 partition)."
fi
