#!/usr/bin/env bash
# One-time environment setup on the cluster. Run this once from a login
# node (needs internet to pip install) -- not part of any sbatch job.
# Adapted from ../fair_ocean_agent/cluster/setup_env.sh (same conda/venv
# create-and-verify logic); this pipeline needs no GPU/LLM backend at all
# (Phase 1 is pure BRENDA/UniProt retrieval), so everything vLLM/Ollama-
# related from that script is dropped here.
#
# Usage (conda, default):
#   git clone https://github.com/helloftroy/phaXYZ_Ocean_Atlas.git
#   cd phaXYZ_Ocean_Atlas
#   ./cluster/setup_env.sh
#
# Reuse an existing conda env instead of creating a new one -- e.g. the
# fair_ocean_agent project's own faire-agent env already has most of this
# package's dependencies (SQLAlchemy, httpx, typer, PyYAML, tenacity, rich):
#   CONDA_ENV_NAME=faire-agent ./cluster/setup_env.sh
#
# Put the env on scratch space if $HOME has a small quota:
#   CONDA_ENV_PREFIX=/scratch/$USER/conda_envs/pha-reference ./cluster/setup_env.sh
#
# Or use a plain venv instead of conda:
#   ENV_MANAGER=venv PYTHON_BIN=python3.11 ./cluster/setup_env.sh
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root (PHA_Ocean_Atlas/)

# Remembers ENV_MANAGER/CONDA_ENV_NAME/CONDA_ENV_PREFIX/MINIFORGE_HOME from
# the last successful run, so re-running with no arguments reuses the SAME
# environment instead of silently defaulting back to a brand-new one.
ENV_CONFIG_FILE="cluster/.env_config"
if [ -f "${ENV_CONFIG_FILE}" ]; then
  # shellcheck source=/dev/null
  source "${ENV_CONFIG_FILE}"
fi

ENV_MANAGER="${ENV_MANAGER:-conda}"

if [ "${ENV_MANAGER}" = "conda" ]; then
  CONDA_ENV_NAME="${CONDA_ENV_NAME:-pha-reference}"
  CONDA_ENV_PREFIX="${CONDA_ENV_PREFIX:-}"
  PYTHON_VERSION="${PYTHON_VERSION:-3.12}"
  MINIFORGE_HOME="${MINIFORGE_HOME:-$HOME/miniforge3}"
  CONDA_SH="${MINIFORGE_HOME}/etc/profile.d/conda.sh"

  if [ ! -f "${CONDA_SH}" ]; then
    echo "conda.sh not found at ${CONDA_SH}." >&2
    echo "Set MINIFORGE_HOME if your (mini)conda/anaconda install lives elsewhere" >&2
    echo "(e.g. MINIFORGE_HOME=\$HOME/miniconda3), or use ENV_MANAGER=venv instead." >&2
    exit 2
  fi
  # shellcheck source=/dev/null
  source "${CONDA_SH}"

  if [ -n "${CONDA_ENV_PREFIX}" ]; then
    CONDA_ENV_TARGET="${CONDA_ENV_PREFIX}"
    CONDA_CREATE_FLAG=(-p "${CONDA_ENV_PREFIX}")
    CONDA_ACTIVATE_TARGET="${CONDA_ENV_PREFIX}"
    export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$(dirname "${CONDA_ENV_PREFIX}")/pip_cache}"
    export CONDA_PKGS_DIRS="${CONDA_PKGS_DIRS:-$(dirname "${CONDA_ENV_PREFIX}")/conda_pkgs}"
    mkdir -p "${PIP_CACHE_DIR}" "${CONDA_PKGS_DIRS}"
    echo "PIP_CACHE_DIR=${PIP_CACHE_DIR}"
    echo "CONDA_PKGS_DIRS=${CONDA_PKGS_DIRS}"
  else
    CONDA_ENV_TARGET="${CONDA_ENV_NAME}"
    CONDA_CREATE_FLAG=(-n "${CONDA_ENV_NAME}")
    CONDA_ACTIVATE_TARGET="${CONDA_ENV_NAME}"
  fi

  if [ -n "${CONDA_ENV_PREFIX}" ]; then
    ENV_EXISTS=0
    [ -d "${CONDA_ENV_PREFIX}" ] && [ -x "${CONDA_ENV_PREFIX}/bin/python" ] && ENV_EXISTS=1
  else
    ENV_EXISTS=0
    conda env list | awk '{print $1}' | grep -qx "${CONDA_ENV_NAME}" && ENV_EXISTS=1
  fi
  if [ "${ENV_EXISTS}" = "1" ]; then
    echo "conda env '${CONDA_ENV_TARGET}' already exists, reusing it."
  else
    echo "Creating conda env at '${CONDA_ENV_TARGET}' (python=${PYTHON_VERSION})..."
    conda create "${CONDA_CREATE_FLAG[@]}" "python=${PYTHON_VERSION}" -y
  fi
  conda activate "${CONDA_ACTIVATE_TARGET}"

  # A shell profile that auto-activates some OTHER virtualenv/conda env can
  # silently win over `conda activate` above -- verify the real interpreter
  # path, not just that the command exited 0 (see fair_ocean_agent's own
  # setup_env.sh, where this was caught live).
  if [ -n "${CONDA_ENV_PREFIX}" ]; then
    EXPECTED_PREFIX="${CONDA_ENV_PREFIX}"
  else
    EXPECTED_PREFIX="$(conda env list | awk -v name="${CONDA_ENV_NAME}" '$1==name {print $NF}')"
  fi
  ACTUAL_PREFIX="$(python -c 'import sys; print(sys.prefix)')"
  if [ "${ACTUAL_PREFIX}" != "${EXPECTED_PREFIX}" ]; then
    echo >&2
    echo "conda activate '${CONDA_ACTIVATE_TARGET}' did not actually take effect:" >&2
    echo "  expected python from: ${EXPECTED_PREFIX}" >&2
    echo "  got python from:      ${ACTUAL_PREFIX}" >&2
    echo "Something else in your shell profile (another virtualenv, pipenv, direnv, ...)" >&2
    echo "is overriding it. Try 'deactivate' first, or run this from a fresh, plain shell." >&2
    exit 2
  fi
  echo "Python: $(python --version) (${ACTUAL_PREFIX})"

  cat > cluster/env_activate.sh <<EOF
# Auto-generated by setup_env.sh -- do not edit by hand, re-run
# setup_env.sh instead (with the same ENV_MANAGER/CONDA_ENV_NAME/
# CONDA_ENV_PREFIX/etc if you're not using the defaults).
source "${CONDA_SH}"
conda activate "${CONDA_ACTIVATE_TARGET}"
$([ -n "${CONDA_ENV_PREFIX}" ] && echo "export PIP_CACHE_DIR=\"${PIP_CACHE_DIR}\"")
$([ -n "${CONDA_ENV_PREFIX}" ] && echo "export CONDA_PKGS_DIRS=\"${CONDA_PKGS_DIRS}\"")
export PYTHONUNBUFFERED=1
_expected_prefix="${EXPECTED_PREFIX}"
_actual_prefix="\$(python -c 'import sys; print(sys.prefix)')"
if [ "\${_actual_prefix}" != "\${_expected_prefix}" ]; then
  echo "conda activate '${CONDA_ACTIVATE_TARGET}' did not take effect in this job's shell" >&2
  echo "(expected \${_expected_prefix}, got \${_actual_prefix}) -- check for a" >&2
  echo "shell-profile-activated virtualenv/conda env overriding it." >&2
  exit 2
fi
unset _expected_prefix _actual_prefix
EOF

  cat > "${ENV_CONFIG_FILE}" <<EOF
# Auto-generated by setup_env.sh -- records this run's settings so a later
# re-run with no arguments reuses the SAME environment. Safe to delete for
# a clean slate; edit by hand to fix one value.
ENV_MANAGER="\${ENV_MANAGER:-conda}"
CONDA_ENV_NAME="\${CONDA_ENV_NAME:-${CONDA_ENV_NAME}}"
CONDA_ENV_PREFIX="\${CONDA_ENV_PREFIX:-${CONDA_ENV_PREFIX}}"
MINIFORGE_HOME="\${MINIFORGE_HOME:-${MINIFORGE_HOME}}"
EOF

elif [ "${ENV_MANAGER}" = "venv" ]; then
  PYTHON_BIN="${PYTHON_BIN:-python3}"
  if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
    echo "PYTHON_BIN='${PYTHON_BIN}' not found on PATH." >&2
    exit 2
  fi
  echo "Python: $("${PYTHON_BIN}" --version)"

  if ! "${PYTHON_BIN}" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)'; then
    echo >&2
    echo "'${PYTHON_BIN}' is too old (this package needs >=3.10). Try:" >&2
    echo "  module avail python 2>&1 | head -30" >&2
    echo "  ./cluster/setup_env.sh   # ENV_MANAGER defaults to conda, which sidesteps this" >&2
    exit 2
  fi

  if [ -d .venv ]; then
    VENV_VERSION="$(.venv/bin/python --version 2>&1 || true)"
    if ! .venv/bin/python -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' 2>/dev/null; then
      echo "Existing .venv was created with an incompatible Python (${VENV_VERSION})." >&2
      echo "Remove it and re-run: rm -rf .venv && PYTHON_BIN=${PYTHON_BIN} ENV_MANAGER=venv ./cluster/setup_env.sh" >&2
      exit 2
    fi
  else
    echo "Creating .venv ..."
    "${PYTHON_BIN}" -m venv .venv
  fi

  EXPECTED_PREFIX="$(pwd)/.venv"
  cat > cluster/env_activate.sh <<EOF
# Auto-generated by setup_env.sh -- do not edit by hand, re-run setup_env.sh instead.
source "${EXPECTED_PREFIX}/bin/activate"
export PYTHONUNBUFFERED=1
_expected_prefix="${EXPECTED_PREFIX}"
_actual_prefix="\$(python -c 'import sys; print(sys.prefix)')"
if [ "\${_actual_prefix}" != "\${_expected_prefix}" ]; then
  echo "venv activation did not take effect in this job's shell" >&2
  echo "(expected \${_expected_prefix}, got \${_actual_prefix}) -- check for a" >&2
  echo "shell-profile-activated virtualenv/conda env overriding it." >&2
  exit 2
fi
unset _expected_prefix _actual_prefix
EOF
  # shellcheck source=/dev/null
  source cluster/env_activate.sh

  cat > "${ENV_CONFIG_FILE}" <<EOF
ENV_MANAGER="\${ENV_MANAGER:-venv}"
PYTHON_BIN="\${PYTHON_BIN:-${PYTHON_BIN}}"
EOF

else
  echo "Unknown ENV_MANAGER='${ENV_MANAGER}'. Use conda (default) or venv." >&2
  exit 2
fi

pip install --upgrade pip
pip install -e ".[dev]"

echo
echo "Environment ready (cluster/env_activate.sh records how run_pha_reference_build.sbatch"
echo "will activate it -- no need to edit that script)."
echo "Next steps:"
echo "  1. cp .env.example .env, then set PHA_REFERENCE_CONTACT_EMAIL for real."
echo "  2. pha-reference init-db"
echo "  3. Submit cluster/run_pha_reference_build.sbatch (or run the CLI directly --"
echo "     this stage needs internet but no GPU, so it also runs fine on a login/service node)."
echo
echo "Quick self-test (no network): python -m pytest tests/unit -q"
